# ──────────────────────────────────────────────
# PDF Report Generator — Create meeting reports
# ──────────────────────────────────────────────
import os
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path
from fpdf import FPDF
from app.config import DATA_DIR

REPORTS_DIR = DATA_DIR / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


class MeetingReportPDF(FPDF):
    """Custom PDF class for meeting reports with header/footer."""

    def __init__(self, title: str = "Meeting Report"):
        super().__init__()
        self.report_title = title
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "AegisNode - Meeting Intelligence", align="L")
        self.cell(0, 8, "CONFIDENTIAL", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(52, 73, 94)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-20)
        self.set_draw_color(52, 73, 94)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        footer_text = f"Generated by AegisNode  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  Page {self.page_no()}/{{nb}}"
        self.cell(0, 8, footer_text, align="C")

    def _section_title(self, title: str):
        """Add a styled section title."""
        self.ln(3)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(52, 152, 219)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 80, self.get_y())
        self.ln(4)

    def _body_text(self, text: str):
        """Add body text."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        # Encode to latin-1 safe text, replacing unsupported chars
        safe_text = text.encode("latin-1", errors="replace").decode("latin-1")
        self.multi_cell(0, 6, safe_text)
        self.ln(2)

    def _bullet_item(self, text: str):
        """Add a bullet point item."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        safe_text = text.encode("latin-1", errors="replace").decode("latin-1")
        self.cell(8)  # indent
        self.cell(5, 6, "-")  # bullet character
        self.multi_cell(0, 6, safe_text)
        self.ln(1)

    def _action_item(self, person: str, task: str, deadline: str):
        """Add a formatted action item."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.cell(8)  # indent

        # Checkbox
        x, y = self.get_x(), self.get_y()
        self.rect(x, y + 1, 4, 4)
        self.cell(7)

        # Person (bold)
        self.set_font("Helvetica", "B", 10)
        safe_person = person.encode("latin-1", errors="replace").decode("latin-1")
        self.cell(0, 6, safe_person, new_x="LMARGIN", new_y="NEXT")

        # Task
        self.set_font("Helvetica", "", 10)
        self.cell(19)
        safe_task = task.encode("latin-1", errors="replace").decode("latin-1")
        self.multi_cell(0, 6, safe_task)

        # Deadline
        if deadline and deadline.lower() != "no deadline":
            self.set_font("Helvetica", "I", 9)
            self.set_text_color(150, 50, 50)
            self.cell(19)
            safe_dl = deadline.encode("latin-1", errors="replace").decode("latin-1")
            self.cell(0, 5, f"Deadline: {safe_dl}", new_x="LMARGIN", new_y="NEXT")
            self.set_text_color(50, 50, 50)

        self.ln(2)


def generate_meeting_report(
    analysis: Dict,
    meeting_id: str,
    title: str = "Meeting Report",
    date: Optional[str] = None,
    duration: Optional[str] = None,
    filename: Optional[str] = None,
) -> str:
    """
    Generate a PDF report from meeting analysis data.

    Args:
        analysis: Dict with summary, key_points, action_items, decisions, follow_up.
        meeting_id: Unique meeting identifier.
        title: Meeting title.
        date: Meeting date string.
        duration: Estimated duration.
        filename: Original transcript filename.

    Returns:
        Path to the generated PDF file.
    """
    pdf = MeetingReportPDF(title=title)
    pdf.alias_nb_pages()
    pdf.add_page()

    # ─── Title Block ─────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(44, 62, 80)
    safe_title = title.encode("latin-1", errors="replace").decode("latin-1")
    pdf.cell(0, 14, safe_title, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Meta info
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    meta_parts = []
    if date:
        meta_parts.append(f"Date: {date}")
    else:
        meta_parts.append(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
    if duration:
        meta_parts.append(f"Duration: {duration}")
    if filename:
        safe_fn = filename.encode("latin-1", errors="replace").decode("latin-1")
        meta_parts.append(f"Source: {safe_fn}")
    meta_parts.append(f"Report ID: {meeting_id[:8]}")

    pdf.multi_cell(0, 5, "  |  ".join(meta_parts))
    pdf.ln(5)

    # Divider
    pdf.set_draw_color(52, 73, 94)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # ─── Summary ─────────────────────────────
    summary = analysis.get("summary", "")
    if summary:
        pdf._section_title("SUMMARY")
        pdf._body_text(summary)

    # ─── Key Discussion Points ───────────────
    key_points = analysis.get("key_points", [])
    if key_points:
        pdf._section_title("KEY DISCUSSION POINTS")
        for point in key_points:
            pdf._bullet_item(point)
        pdf.ln(2)

    # ─── Action Items ────────────────────────
    action_items = analysis.get("action_items", [])
    if action_items:
        pdf._section_title("ACTION ITEMS")
        for item in action_items:
            if isinstance(item, dict):
                pdf._action_item(
                    item.get("person", "Unassigned"),
                    item.get("task", ""),
                    item.get("deadline", "No deadline"),
                )
            else:
                pdf._bullet_item(str(item))
        pdf.ln(2)

    # ─── Decisions Made ──────────────────────
    decisions = analysis.get("decisions", [])
    if decisions:
        pdf._section_title("DECISIONS MADE")
        for decision in decisions:
            pdf._bullet_item(decision)
        pdf.ln(2)

    # ─── Follow-Up ───────────────────────────
    follow_up = analysis.get("follow_up", [])
    if follow_up:
        pdf._section_title("FOLLOW-UP")
        for item in follow_up:
            pdf._bullet_item(item)
        pdf.ln(2)

    # ─── Save ────────────────────────────────
    output_filename = f"meeting_report_{meeting_id}.pdf"
    output_path = str(REPORTS_DIR / output_filename)
    pdf.output(output_path)

    return output_path
